### ISSUE TITLE
[query] Add some algebraic interface for generating SQL

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#273]
The query algebrizer (see #243 and follow-on work) will be producing lots of SQL and joining/intersecting/unioning it in non-trivial ways.  We'll want a statically typed representation of this SQL to constrain the space of SQL queries we produce, hopefully to the set of queries that are syntactically valid SQL.

This is similar to [the Honeysql Clojure library](https://github.com/jkk/honeysql).  We might be able to just use [the Diesel query_builder crate](http://docs.diesel.rs/diesel/query_builder/index.html).

This isn't a good first bug, since it's intimately tied to the query generation work and will need to grow with it, and since it's likely to want an "advanced" Rust implementation.

**Comment by ncalexan** [comment]
@rnewman just alerting you to this ticket; you might drop any thinking you've done about this here.

**Comment by rnewman** [comment]
I did a brief survey of this when fleshing out #133, and didn't find much more than Diesel. (I linked this issue from the backlog.)

SQL is very complex, and there are so many different implementations that subtly differ, so a general-purpose SQL generator is a pain to get right.

Further, when considering intermediate representations — which we would be using in order to accumulate clauses for later use, as opposed to one-shot macro-like invocations — it's an easy place to accidentally introduce inefficiencies: allocating new structures and copying strings.

At the algebrizing stage I'm still mostly working with domain concepts, like `EqualsEntity` relating an aliased column to an entity ID. The next stage, planning, is where we'll run into the need to turn those things into fragments of SQL. Our generated queries are relatively simple, so it might be possible to get away without implementing this at all. Alternatively, we might end up growing a library like this as we go.

**Comment by rnewman** [comment]
I believe most of Diesel is unsuitable for our purposes.

Its query builder:

- [Can't select from views](https://github.com/diesel-rs/diesel/issues/566).
- [Doesn't support recursive queries](https://github.com/diesel-rs/diesel/issues/356).
- As far as I can tell doesn't name-qualify or alias tables, making self-joins impossible.

I suspect there would be further issues with features like `EXISTS` filters, and its sequence-of-joins approach is less ergonomic for our constraint-based queries.

Additionally, the Diesel query builder is pretty much entirely undocumented. It's not clear how one would do things we need to do, like maintain a reference to a particular use of a table in a query in order to project correctly. It's very much intended for use by the Diesel ORM, which is itself [quite](https://github.com/diesel-rs/diesel/issues/332) [limited](https://github.com/diesel-rs/diesel/issues/398).

We might be able to reuse their `QueryBuilder` class, which is effectively an interface for an escaping/syntax-aware `StringBuilder`, similar to `std::fmt::Formatter`. But they discourage the use of that API.

**Comment by ncalexan** [comment]
@rnewman thanks for doing that digging.  Sounds like we should grow our own `honeysql`-like ADT for representing SQL.

**Comment by rnewman** [comment]
This is done, albeit not general-purpose.
